const link_map = {
    'About': '/about',
    'News': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Discord Server': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Twitter': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Facebook': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Youtube': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Contact Us': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Privacy Policy': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Licensing': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Terms & Conditions': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'iOS': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Android': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Windows': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'MacOS': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Instagram': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Github': 'https://github.com/TannerHornsby7/sauna-web',
    'Video': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Survey': 'https://forms.gle/NoMAhsTmPbQGxfhv7',
    'Reddit': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'CNVC': 'https://polsky.uchicago.edu/wp-content/uploads/2021/09/Polsky_logo_stack-1.png',
    'CNVC Website': 'https://polsky.uchicago.edu/programs-events/new-venture-challenge/college-new-venture-challenge/',
}

export default link_map;